# ============================================================
# MEMÓRIA DO GRADLE
# ============================================================

org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError

# Limita a quantidade de tarefas executadas simultaneamente.
# Ajuda computadores com pouca memória RAM.
org.gradle.workers.max=2


# ============================================================
# ANDROID
# ============================================================

android.useAndroidX=true
android.enableJetifier=true


# ============================================================
# COMPATIBILIDADE FLUTTER / ANDROID
# ============================================================

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false

# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false